//= require moment
//= require moment.es
//= require bootstrap-datetimepicker

//= require jquery-ui.custom.min
//= require jquery.ui.touch-punch.min
//= require fullcalendar.min

crearCalendar = ()->

  data = $("#calendar").data("horario")
  
  hash_colores = $("#calendar").data("labels")

  console.log hash_colores

  detalles= []

  if data[0].horaSalida != undefined
    i = data.length - 1
    while i >= 0
      data[i]
      detalles.push
        title: data[i].codigo_proyecto
        start: data[i].horaEntrada
        end: data[i].horaSalida
        proyecto_id: data[i].proyecto_id
        className: 'label-' + hash_colores[ data[i].proyecto_id ]
      i--
  else
    data = {}


  # new Date(year, month, day, hours, minutes, seconds, milliseconds);
  calendar = $('#calendar').fullCalendar(
    buttonHtml:
      prev: '<i class="ace-icon fa fa-chevron-left"></i>'
      next: '<i class="ace-icon fa fa-chevron-right"></i>'
    defaultDate: moment('2017-05-01')
    header: {}
    allDaySlot: false
    defaultView: 'basicWeek'
    timeFormat: 'HH:mm'
    displayEventEnd: true
    firstDay: 1
    height: 200
    width: 800
    events: detalles
    allDayDefault: false
    forceEventDuration: true
  )
  $('.fc-toolbar').hide()

  $('.fc-day-header.fc-sun:first').html 'Domingo'
  $('.fc-day-header.fc-mon:first').html 'Lunes'
  $('.fc-day-header.fc-tue:first').html 'Martes'
  $('.fc-day-header.fc-wed:first').html 'Miercoles'
  $('.fc-day-header.fc-thu:first').html 'Jueves'
  $('.fc-day-header.fc-fri:first').html 'Viernes'
  $('.fc-day-header.fc-sat:first').html 'Sabado'

$(document).ready ->
  fecha = new Date dateServerRender()
  
  crearCalendar()

  # $('#fecha').datetimepicker
  #   format: 'MM/YYYY'
  #   date: fecha

  $('#fecha').datetimepicker
    format: "MM/YYYY"
    viewMode: "months"
    date: fecha

  $("#bt-filtrar").click ->
    $("#spin-ajax").show()
    $("#table-customized").empty()
    $.post( "/empleados/#{$("#empleado_id").val()}/ajax_table_por_mes", $("#parametros").serialize())
      .done (data) ->
        $("#spin-ajax").hide()
        $("#table-customized").append data


  






# # CALCULO DE LAS HORAS DE LOS DETALLES DEL HORARIO
# # Y SETEO. TODO ESTO SE HACE DESPUES DEL RENDERIZADO.
# $('.fc-day-header').slice(-7).html('00:00 hs').css('background-color', '#aeff70').css 'color', 'black'
# $('.fc-day-header').slice(-7).each (i, v) ->
#   duration_milliseconds = dayTotals[i + 1].asMilliseconds()
#   duration_semanal += duration_milliseconds
#   # Control Diario
#   $(v).html moment.utc(duration_milliseconds).format('HH:mm') + ' hs'
#   if 32400000 < duration_milliseconds
#     $(v).css 'background-color', 'red'
#     $(v).css 'color', 'white'
#   else
#     $(v).css 'background-color', '#aeff70'
#     $(v).css 'color', 'black'
#   return
# # Control Semanal
# dias = moment.duration(duration_semanal).days()
# horas = moment.duration(duration_semanal).hours()
# minutos = moment.duration(duration_semanal).minutes()
# hora_semanal = ('00' + dias * 24 + horas).slice(-2) + ':' + ('00' + minutos).slice(-2)
# if duration_semanal > 172800000
#   $('#horas-semanal').html(hora_semanal + ' hs Exedido!').removeClass('green').addClass 'red'
# else
#   $('#horas-semanal').html(hora_semanal + ' hs').removeClass('red').addClass 'green'
# $('#empleado-tab').click()

# # ---
# # generated by js2coffee 2.2.0





